COVID/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',include("accountsApp.urls")),
    path('',include("articlesApp.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)






"""COVID URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))

"""

articlesApp/urls.py
from django.urls import path
from articlesApp import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'articlesApp'
urlpatterns = [
    path("home", views.main, name="home"),
    path("main", views.main, name="main"),
    path("add-category", views.category, name="add-category"),
    path("add-article", views.article, name="add-article"),
    path("", views.feed, name="feed"),
    path("about", views.about, name="about"),
    path("profile", views.profile, name="profile"),
    path("contact", views.contact, name="contact"),
    path("posts/<int:num>" , views.post, name="post"),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

articlesApp/models.py
from djongo import models

# Create your models here.


class Categories(models.Model):
    
    name = models.CharField(max_length=10)
    description = models.CharField(max_length=100)

    class Meta :
        abstract : True 
    
    def __str__(self):
        return self.name

    objects = models.DjongoManager()



class Articles(models.Model):
    
    title = models.CharField(max_length=100, default='ANONYMOUS')
    contributor = models.CharField(max_length=30, default='ANONYMOUS')
    source = models.CharField(max_length=1000, default='unproven')
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, default=1)
    image_link = models.TextField( default='ANONYMOUS')
    html_text = models.TextField(default='<body> Empty set </body>')
    

    class Meta :
        abstract : True 
    
    def __str__(self):
        return self.contributor+" added a "+self.category.__str__()+" about :"+self.title

    objects = models.DjongoManager()

articlesApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Articles, Categories


def set_session(request):
    return request

def exists_session(request):
    return False


# Main : /articles/index
def main(request):
    
    if request.method == 'POST' :
        return main_post(request)

    else :
        if request.method == 'GET' :
            return main_get(request)
        else :
            return HttpResponse("404 not found error please contact administrator")


def main_get(request):
    return render(request,'articlesApp/index.html')
def main_post(request):
    if request.POST.get('category', '') :
        return redirect('articlesApp:add-category')
    
    if request.POST.get('article', '') :
        return redirect('articlesApp:add-article')
    return HttpResponse("Internal error. Please contact administrator")


# Category add page /articles/add-category
def category(request):
    if request.method == 'POST' :
        return category_post(request)
    else :
        if request.method == 'GET' :
            return category_get(request)
        else :
            return HttpResponse("65 not found error please contact administrator")


def get_next_id(a_list):
    return len(a_list)

def name_to_id(name):
    category =  Categories.objects.filter(name=name)
    _id = 0
    for query in category:
        _id = query.id
    return _id

def category_get(request):
    categories = Categories.objects.all()
    return render(request,'articlesApp/add_category.html',
                    {'categories':categories}
                 )
def category_post(request):
    name = request.POST.get('name','')
    description = request.POST.get('description','')
    bol = True
    objects = Categories.objects.all()

    if (name ):
        bol = bol & True 
    if (description) :
        bol = bol & True
    if (len(name) < 10):
        bol = bol & True
    if ( (len(name) > 10) | (len(description) > 100) ):
        bol = bol & False
    for x in Categories.objects.all() :
        if( x.name == name ):
            bol = bol & False
    if bol :
        Categories.objects.mongo_insert_one({
            'id': get_next_id(objects),
            'name':name,
            'description':description
        })
        return render(request,'articlesApp/index.html')
    else :
        return render(request,'articlesApp/add_category.html',{'categories':objects})
    


# Article add page /articles/add-article
def article(request):
    if request.method == 'POST' :
        return article_post(request)

    else :
        if request.method == 'GET' :
            return article_get(request)
        else :
            return HttpResponse("66 not found error please contact administrator")


def article_get(request):
    return render(request,'articlesApp/add_article.html', {'categories':Categories.objects.all()})


def article_post(request):
    title = request.POST.get('title','')
    contributor = request.POST.get('contributor','ANONYMOUS')
    image_link = request.POST.get('image_link','')
    source = request.POST.get('source','unapproved')
    category_name = request.POST.get('category','')
    
    category_id = name_to_id(category_name)
    
    if (category_id < 0):
        return HttpResponse('67 An error occurent please contact administrator')
    html_file = request.POST.get('html_file','')
    try :
        Articles.objects.mongo_insert_one({
                'id' : get_next_id(Articles.objects.all()),
                'title': title,
                'contributor':contributor,
                'image_link':image_link,
                'source':source,
                'html_text':html_file,
            })
    except Exception as e: 
        return HttpResponse("68 error please contact administrator")

    return article_get(request)

    

# feed front page
def feed(request):
    if request.method == 'POST' :
        return HttpResponse("FEED POST")

    else :
        if request.method == 'GET' :
            return render(request,'articlesApp/feed.html')
        else :
            return HttpResponse("69 not found error please contact administrator")


# about page
def about(request):
    if request.method == 'POST' :
        return HttpResponse("about POST")

    else :
        if request.method == 'GET' :
            return HttpResponse("ABOUT GET")
        else :
            return HttpResponse("70 not found error please contact administrator")


# profile front page
def profile(request):
    if request.method == 'POST' :
        return HttpResponse("profile POST")

    else :
        if request.method == 'GET' :
            return HttpResponse("Not developped yet")
        else :
            return HttpResponse("71 not found error please contact administrator")


# contact front page
def contact(request):
    if request.method == 'POST' :
        return HttpResponse("contact POST")

    else :
        if request.method == 'GET' :
            return HttpResponse("contact GET")
        else :
            return HttpResponse("72 not found error please contact administrator")


def post(request, num):
    # fetch post by name
    if request.method == 'POST' :
        return HttpResponse("{} POST".format(num))
    if request.method == 'GET' :
            #return HttpResponse("{} GET".format(name))
            return render(request,'articlesApp/post.html')
    else :
        return HttpResponse("73 not found error please contact administrator")

articlesApp/templates/articlesApp/about.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

articlesApp/templates/articlesApp/feed.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog</title>

  <!-- Bootstrap core CSS -->
  {% load static %}
  <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  {% load static %}
  <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  {% load static %}
  <link href="{% static "css/clean-blog.min.css" %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'articlesApp:feed' %}">Clean Blog</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articlesApp:feed' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articlesApp:about' ">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articlesApp:profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articlesApp:contact' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Clean Blog</h1>
            <span class="subheading">See what people are talking about</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          <a href="{% url 'articlesApp:post' 0 %}">
            <h2 class="post-title">

              Man must explore, and this is exploration at its greatest

            </h2>
            <h3 class="post-subtitle">
            
              Problems look mighty small from 150 miles up

            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Nechi Aziz</a>
            on September 24, 2019</p>
        </div>

        <hr>
        




        
        <!-- Pager -->
        <div class="clearfix">
          <a class="btn btn-primary center" href="#">Load more &rarr;</a>
        </div>


      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  {% load static %}
  <script src="{% static "vendor/jquery/jquery.min.js" %}" ></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  <!-- Custom scripts for this template -->
  {% load static %}
  <script src="{% static "js/clean-blog.min.js" %}" ></script>

</body>
</html>

articlesApp/templates/articlesApp/post.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
    Man must explore, and this is exploration at its greatest
  </title>

  <!-- Bootstrap core CSS -->
  {% load static %}
  <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  
  <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static "css/clean-blog.min.css" %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Clean Blog</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articlesApp:feed' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articlesApp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articlesApp:profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articlesApp:contact' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image:  url({% static 'img/post-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>Man must explore, and this is exploration at its greatest</h1>
            <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
            <span class="meta">Posted by
              <a href="#">Start Bootstrap</a>
              on August 24, 2019</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>

          <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

          <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>

          <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

          <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

          <h2 class="section-heading">The Final Frontier</h2>

          <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

          <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

          <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

          <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>

          <h2 class="section-heading">Reaching for the Stars</h2>

          <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>

          <a href="#">
            <img class="img-fluid" src="{% static 'img/post-sample-image.jpg' %}" alt="">
          </a>
          <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>

          <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>

          <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>

          <p>Placeholder text by
            <a href="http://spaceipsum.com/">Space Ipsum</a>. Photographs by
            <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>.</p>
        </div>
      </div>
    </div>
  </article>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static "js/clean-blog.min.js" %}"></script>

</body>

</html>